name: pubspec
description: >
  A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files
version: 0.0.1
author: Anders Holmgren <andersmholmgren@gmail.com>
#homepage: https://www.example.com
dependencies:
  path: '^1.3.5'
  pub_semver: '^1.1.0'
dev_dependencies:
  unittest: any
