author: Anders Holmgren <andersmholmgren@gmail.com>
description: A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files
homepage: https://github.com/Andersmholmgren/pubspec
name: pubspec
version: 0.1.2
dependencies: 
  path: ^1.6.2
  pub_semver: ^1.4.2
  stuff: ^0.1.0
  yaml: ^2.1.15
dev_dependencies: 
  test: ^1.3.3
environment: 
  sdk: '>=2.2.2 <3.0.0'
