author: Anders Holmgren <andersmholmgren@gmail.com>
description: A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files
homepage: https://github.com/Andersmholmgren/pubspec
name: pubspec
version: 1.0.0-nullsafety.0
dependencies: 
  path: ^1.8.0-nullsafety.3
  pub_semver: ^2.0.0
  yaml: ^3.0.0
  uri: 1.0.0
    
    
dev_dependencies: 
  test: ^1.3.3
environment: 
  sdk: '>=2.12.0-0 <3.0.0'
