author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files"
homepage: "https://github.com/Andersmholmgren/pubspec"
name: "pubspec"
version: "0.0.14"
dependencies: 
  path: ">=1.3.9"
  pub_semver: ">=1.2.3"
  stuff:
    path: ../stuff
  yaml: ">=2.1.8"
  yamlicious:
    path: ../yamlicious
dev_dependencies: 
  test: ">=0.12.7"
environment: 
  sdk: ">=2.0.0 <3.0.0"
