author: Anders Holmgren <andersmholmgren@gmail.com>
description: A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files
homepage: https://github.com/Andersmholmgren/pubspec
name: pubspec
version: 0.0.6
dependencies: 
  path: '^1.3.5'
  pub_semver: '^1.1.0'
  yaml: '^2.1.2'
  stuff: 
    path: /Users/blah/dart/jefe_jefe/jefe_container_root/stuff
  yamlicious: 
    path: /Users/blah/dart/jefe_jefe/jefe_container_root/yamlicious
dependency_overrides: 
dev_dependencies: 
  test: '^0.12.7'
environment: 
  sdk: '>=1.9.0 <2.0.0'
