name: pubspec
description: >
  A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files
version: 0.0.2
author: Anders Holmgren <andersmholmgren@gmail.com>
homepage: https://github.com/Andersmholmgren/pubspec
environment:
  sdk: ">=1.9.0 <2.0.0"
dependencies:
  path: '^1.3.5'
  pub_semver: '^1.1.0'
  yamlicious: '^0.0.1'
  yaml: '^2.1.2'
dev_dependencies:
  unittest: any
