author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files"
homepage: "https://github.com/Andersmholmgren/pubspec"
name: "pubspec"
version: "0.1.0"
dependencies:
  path: "^1.6.2"
  pub_semver: "^1.4.2"
  yaml: "^2.1.15"
  stuff: 
    path: "../stuff"
  yamlicious: 
    path: "../yamlicious"
dev_dependencies:
  test: "^1.3.3"
environment: 
  sdk: ">=2.0.0 <3.0.0"
